# Generated by Django 5.1.1 on 2024-09-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_content', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='카테고리')),
                ('user_id', models.CharField(max_length=100, verbose_name='유저ID')),
            ],
        ),
    ]
